### ISSUE TITLE
Style and Linter Error in Generated Code

### ISSUE THREAD

**Issue by qwordy** [Azure/autorest.az#800] opened 2021-03-26 06:27 UTC
**Why do you need this feature?**

I must fix style error in generated code, otherwise I can't merge. But generated code should not be changed.

**Is your feature request related to a problem? Please describe.**

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/preview/2020-10-01-preview/cloudService.json

1. example_steps.py: W391 blank line at end of file.
2. commands.py:26:0: C0330: Wrong hanging indentation before block (add 4 spaces).
```
    with self.command_group(
        'cloud-service role-instance',
```
It should be
```
    with self.command_group(
            'cloud-service role-instance',
```
3. No command. Only name.
```
helps['cloud-service role-instance wait'] = """
    type: command
    short-summary: Place the CLI in a waiting state until a condition of the cloud-service role-instance \
is met.
    examples:
      - name: Pause executing next line of CLI script until the cloud-service role-instance is \
successfully deleted.
      - name: Pause executing next line of CLI script until the cloud-service role-instance is \
successfully created.
"""
```
```
helps['cloud-service wait'] = """
    type: command
    short-summary: Place the CLI in a waiting state until a condition of the cloud-service is met.
    examples:
      - name: Pause executing next line of CLI script until the cloud-service is successfully created.
"""
```
4. All "cloud_service_name" miss help.
```
    with self.argument_context('cloud-service role-instance list') as c:
        c.argument('resource_group_name', resource_group_name_type)
        c.argument('cloud_service_name', type=str, help='')
```

**Describe the solution you'd like**

Fix style and linter error

**Describe alternatives you've considered**

**Additional context**

**Comment by changlong-liu** [comment] 2021-04-01 08:43
Hi @qwordy, would you try latest private release, thanks!

**Comment by changlong-liu** [comment] 2021-04-02 08:05
Hi @qwordy , the latest private release should have fix item 1. I will check the item 2~4

**Comment by changlong-liu** [comment] 2021-04-06 06:01
Hi @qwordy,

I checked as below:
item 1: fixed in latest private release
item2: we are using Python "black" to format the code, seems the current result is correct. And "azdev style cloudservice" don't complain about it in my side.
item3: should be related to swagger example, I can't reproduce this in latest swagger. 
item4: there is no "description" for this field in swagger.

**Comment by qwordy** [comment] 2021-04-06 06:34
Thanks, changlong.
I wonder how the swagger file gets merged. It misses description.

**Comment by changlong-liu** [comment] 2021-04-22 09:00
close this first. for swagger concern, we can propose lint rule

**Closed by changlong-liu** 2021-04-22 09:00 UTC
